"""Trajectory memory documents and action parsing shared by the TextWorld environments."""

from __future__ import annotations

import re
import string
from dataclasses import dataclass, field

ACTION_PATTERN = re.compile(r"\[ACTION:\s*([^\]]+)\]", re.IGNORECASE)
ALLOWED_ACTION_CHARS = frozenset(string.ascii_letters + string.digits + string.whitespace + "-_.,!?'")
FALLBACK_PREFIXES = ("Action:", "I will", "I'll", "Let me", "I would", "I should")
MAX_ACTION_CHARS = 200


def parse_action(response: str) -> str:
    """Extract the game command from a model response.

    The command is the text inside the first ``[ACTION: ...]`` tag. Without a tag, the first line after any
    ``</think>`` block is used, minus a leading phrase such as "I will". Characters the game parser cannot handle are
    removed and the command is capped at ``MAX_ACTION_CHARS``.

    Args:
        response: Raw text generated by the model for one turn.

    Returns:
        The sanitized command, or an empty string if nothing usable was found.
    """
    response = (response or "").encode("utf-8", errors="ignore").decode("utf-8", errors="ignore")
    if not response:
        return ""

    match = ACTION_PATTERN.search(response)
    if match:
        command = match.group(1).strip()
    else:
        command = response.replace("<think>", "").replace("</think>", "").strip()
        if "</think>" in response:
            command = response.split("</think>", 1)[1].strip() or command
        for prefix in FALLBACK_PREFIXES:
            if command.lower().startswith(prefix.lower()):
                command = command[len(prefix) :].strip()
        if "\n" in command:
            command = command.split("\n", 1)[0].strip()
        command = command.strip("\"'.")

    command = "".join(char for char in command if char in ALLOWED_ACTION_CHARS)
    return command.strip()[:MAX_ACTION_CHARS]


@dataclass
class Turn:
    """One completed turn: what the agent saw, what it did and what it earned."""

    turn: int
    observation: str
    action: str
    reward: float
    score: int


@dataclass
class TrajectoryMemory:
    """Groups completed turns into text documents for the memory modality.

    Every ``turns_per_document`` completed turns become one document. Only the most recent ``max_documents`` documents
    are kept, and each observation is cut to ``max_observation_chars`` characters (0 keeps it whole).
    """

    turns_per_document: int
    max_documents: int
    max_observation_chars: int = 0
    documents: list[str] = field(default_factory=list)
    _segment: list[Turn] = field(default_factory=list)

    def add_turn(self, turn: int, observation: str, action: str, reward: float, score: int) -> None:
        """Record a completed turn and close the current document once it holds enough turns.

        Args:
            turn: 1-based turn index.
            observation: Observation the agent acted on.
            action: Command sent to the game.
            reward: Reward returned for this turn.
            score: Game score after this turn.
        """
        if self.max_observation_chars > 0:
            observation = observation[: self.max_observation_chars]
        self._segment.append(Turn(turn=turn, observation=observation, action=action, reward=reward, score=score))
        if len(self._segment) >= self.turns_per_document:
            self.flush()

    def flush(self) -> None:
        """Close the current document even if it holds fewer than ``turns_per_document`` turns."""
        if not self._segment:
            return
        self.documents.append(self._render(self._segment))
        self.documents = self.documents[-self.max_documents :]
        self._segment = []

    @staticmethod
    def _render(segment: list[Turn]) -> str:
        """Format a run of turns as a document.

        Args:
            segment: Consecutive completed turns.

        Returns:
            The document text.
        """
        total_reward = sum(turn.reward for turn in segment)
        score_change = segment[-1].score - segment[0].score
        lines = [
            f"Turns {segment[0].turn}-{segment[-1].turn} | Reward: {total_reward} | Score Change: {score_change}",
            "",
        ]
        for turn in segment:
            lines.append(f"Turn {turn.turn}:")
            if turn.observation:
                lines.append(f"Obs: {turn.observation}")
            action_line = f"Act: {turn.action}"
            if turn.reward != 0:
                action_line += f" -> Reward: {turn.reward}"
            lines.append(action_line)
            lines.append("")
        return "\n".join(lines).strip()
